plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'ru.abrosimov'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            artifactId = 'jenkins'
        }
    }

    repositories {
        mavenLocal()
    }
}
